---
- name: Install Influx DB 2 CLI
  package:
    name: influxdb2-cli

- name: Check bucket
  command: influx bucket list -n "{{ influxdb_bucket }}"
  register: result
  ignore_errors: yes
  changed_when: false

- name: Influx DB 2 initial setup # noqa risky-shell-pipe no-changed-when
  command: >
    influx setup
    --org "{{ influxdb_org }}"
    --bucket "{{ influxdb_bucket }}"
    --username "{{ influxdb_user }}"
    --password "{{ influxdb_password }}"
    --host http://{{ influxdb_host }}:8086
    --retention "{{ influxdb_retention }}"
    --force
  when: result.rc != 0

- name: Create authentication config # noqa risky-shell-pipe
  command: >
    influx config create
    --config-name "{{ influxdb_authentication_config_name }}"
    --host-url http://{{ influxdb_host }}:8086
    --org "{{ influxdb_org }}"
    --active
  args:
    creates: /root/.influxdbv2/configs

- name: Register bucket id # noqa risky-shell-pipe
  shell: >
    influx bucket list
    | grep -P "\s{{ influxdb_bucket }}\s"
    | grep -Po "^\S*"
  ignore_errors: yes
  register: bucket_id
  changed_when: false

- name: List bucket id # noqa risky-shell-pipe
  shell: >
    influx auth list
    | grep "{{ bucket_id.stdout}}"
  ignore_errors: yes
  register: token_list
  changed_when: false

- name: Create token für bucket # noqa risky-shell-pipe no-changed-when
  shell: >
    influx auth create
    --write-bucket "{{ bucket_id.stdout }}"
    |grep -v ^ID
    | awk '{print $2}'
  register: bucket_token
  when: token_list.rc != 0

- name: Read tokens # noqa risky-shell-pipe
  shell: >
    influx auth list
    | grep "{{ bucket_id.stdout}}"
    | awk '{print $2}'
  register: token_list
  changed_when: false
- name: Save token
  set_fact:
    token: "{{ token_list.stdout }}"
