---
- name: Ensure InfluxDB key is available (Debian)
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Ensure InfluxDB apt repository is configured (Debian)
  apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/influxdb.gpg] https://repos.influxdata.com/{{ ansible_distribution }} {{ ansible_distribution_release }} stable
    state: present

- name: Refresh apt cache
  apt:
    update_cache: yes
