---
- name: Ensure gpg exists, for signing keys
  ansible.builtin.apt:
    name:
      - gpg
      - gpg-agent
    state: present

- name: Ensure InfluxDB key is available (Debian)
  apt_key:
    url: https://repos.influxdata.com/influxdata-archive.key
    state: present

- name: Ensure InfluxDB apt repository is configured (Debian)
  apt_repository:
    repo: >
      deb
      https://repos.influxdata.com/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }}
      stable
    state: present

- name: Refresh apt cache
  apt:
    update_cache: yes
