---
- name: Manage rpm repositories
  import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Manage deb repositories
  import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install InfluxDB 2
  package:
    name: influxdb2

- name: Start InfluxDB 2
  service:
    name: influxdb
    state: started

- name: Setup bucket
  import_tasks: bucket.yml

- name: Setup backup
  import_tasks: backup.yml
