---

- name: Manage rpm repositories
  import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Manage deb repositories
  import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Grafana
  package:
    name: grafana

- name: Start Grafana
  service:
    name: grafana-server
    state: started
    enabled: yes
