---

- name: Converge
  hosts: all
  collections:
    - netways.graphing
  tasks:

    - name: "Include InfluxDB"
      include_role:
        name: influxdb

    - name: "Include Grafana"
      include_role:
        name: grafana
  vars:
    influxdb_host: graphing-default
